apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: iot
  namespace: iot
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-tenant-iot
    namespace: flux-system
  path: ./apps/iot
  prune: true
  timeout: 5m
