apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: mongodb
  namespace: iot
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-tenant-iot
    namespace: flux-system
  path: ./infrastructure/mongodb
  prune: true
  timeout: 5m
