apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: iot
spec:
  chart:
    spec:
      chart: iot
      sourceRef:
        kind: HelmRepository
        name: mmontes
        namespace: flux-system
      version: "0.2.0"
  interval: 1h0m0s
  valuesFrom:
    - kind: ConfigMap
      name: iot
