apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: iot
resources:
  - sealedsecret.yaml
  - helmrelease.yaml
configMapGenerator:
  - name: iot
    files:
      - values.yaml=values.yaml
configurations:
  - kustomizeconfig.yaml
