apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mongodb
spec:
  releaseName: mongodb
  chart:
    spec:
      chart: mongodb
      sourceRef:
        kind: HelmRepository
        name: mmontes
        namespace: flux-system
      version: "0.5.0"
  interval: 5m
  values:
    image:
      repository: mongo
      pullPolicy: IfNotPresent
      tag: 4.4.13

    storage:
      size: 8Gi
      className: rook-ceph
      accessModes:
        - "ReadWriteOnce"

    backup:
      enabled: true
      cron: "0 1 * * *"
      volume:
        nfs:
          enabled: true
          server: 10.0.0.50
          path: /volume1/iot/mongodb
        pvc:
          enabled: false

    livenessProbe:
      failureThreshold: 5
      initialDelaySeconds: 30
      periodSeconds: 30
      successThreshold: 1
      timeoutSeconds: 5

    readinessProbe:
      failureThreshold: 5
      initialDelaySeconds: 30
      periodSeconds: 30
      successThreshold: 1
      timeoutSeconds: 5

    resources:
      requests:
        cpu: 500m
        memory: 700Mi
      limits:
        memory: 700Mi

    podDisruptionBudget:
      enabled: true
      minAvailable: 1

    prometheus-mongodb-exporter:
      mongodb:
        uri: "mongodb://mongodb:27017"
      serviceMonitor:
        enabled: true
